name: MMA-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - comm=0.1.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - ipykernel=6.23.3
  - ipython=8.14.0
  - jedi=0.18.2
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1u
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=3.8.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - pip:
    - branca==0.6.0
    - git+https://github.com/openai/CLIP.git
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - et-xmlfile==1.1.0
    - filelock==3.12.0
    - folium==0.14.0
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - ftfy==6.1.1
    - h5py==3.8.0
    - huggingface-hub==0.15.1
    - idna==3.4
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - llvmlite==0.40.0
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.1
    - nltk==3.8.1
    - numba==0.57.0
    - numpy==1.24.3
    - openpyxl==3.1.2
    - pandas==2.0.1
    - pillow==9.5.0
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - pyqt6==6.5.1
    - pyqt6-qt6==6.5.1
    - pyqt6-sip==13.5.1
    - pyqt6-webengine==6.5.0
    - pyqt6-webengine-qt6==6.5.1
    - pytz==2023.3
    - pyyaml==6.0
    - rank-bm25==0.2.2
    - regex==2023.6.3
    - requests==2.31.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - shapely==2.0.1
    - smart-open==6.3.0
    - sympy==1.12
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - torch==2.0.0
    - torchvision==0.15.1
    - tqdm==4.65.0
    - transformers==4.29.2
    - tzdata==2023.3
    - umap-learn==0.5.3
    - urllib3==2.0.2
    - wordcloud==1.9.2
    - xgboost==1.7.6
    - xmltodict==0.13.0
