name: mma2023
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - comm=0.1.2
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - folium=0.14.0
  - freetype=2.12.1
  - geos=3.9.1
  - giflib=5.2.1
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonlines=2.0.0
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.8
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pyzmq=25.1.0
  - readline=8.2
  - seaborn=0.12.2
  - setuptools=67.8.0
  - shapely=2.0.1
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - git+https://github.com/openai/CLIP.git
      - contourpy==1.0.7
      - filelock==3.12.1
      - flatten-json==0.1.13
      - fonttools==4.39.4
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - h5py==3.8.0
      - huggingface-hub==0.15.1
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - llvmlite==0.40.0
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - nltk==3.8.1
      - numba==0.57.0
      - packaging==23.1
      - pandas==2.0.1
      - pillow==9.5.0
      - pynndescent==0.5.10
      - pyqt6==6.5.0
      - pyqt6-qt6==6.5.0
      - pyqt6-sip==13.5.1
      - pyqt6-webengine==6.5.0
      - pyqt6-webengine-qt6==6.5.1
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sympy==1.12
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==2.0.0
      - torchvision==0.15.1
      - tqdm==4.65.0
      - transformers==4.30.2
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - umap-learn==0.5.3
      - urllib3==2.0.3
      - wcwidth==0.2.6
      - wordcloud==1.9.2
      - xgboost==1.7.6
      - xmltodict==0.13.0
      - zipp==3.15.0
